version: '3.2'
networks:
  mynetwork:
    driver: bridge

volumes:
  images:

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=dmitrii
      - POSTGRES_PASSWORD=dmitrii
      - LOG_DESTINATION=stderr
      - POSTGRES_DB=twitter_db
      - LOGGING_COLLECTOR=on
      - LOG_DIRECTORY=/var/log/postgresql
    ports:
      - '5432:5432'
    volumes:
      - ./db/:/var/lib/postgresql/data
    networks:
      - mynetwork

  app:
    build: twitter/
    ports:
      - '5050:5050'
    networks:
      - mynetwork
    depends_on:
      - postgres
    volumes:
      - images:/app/media

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/share/nginx/html
      - images:/usr/share/nginx/html/images
    networks:
      - mynetwork

