version: '3.2'
networks:
  mynetwork:
    driver: bridge

volumes:
  media:

services:
  postgres:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      LOG_DESTINATION: stderr
      LOGGING_COLLECTOR: on
      LOG_DIRECTORY: /var/log/postgresql
    ports:
      - '5432:5432'
    volumes:
      - ./db/:/var/lib/postgresql/data
    networks:
      - mynetwork


  app:
    build: twitter/
    env_file:
      - .env
    environment:
      - ENV=debug
    ports:
      - '5050:5050'
    networks:
      - mynetwork
    volumes:
      - media:/app/media
    depends_on:
      - postgres

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/share/nginx/html
      - media:/usr/share/nginx/html/media
    depends_on:
      - app
    networks:
      - mynetwork

